import { PrismaClient, ProductCategory, ProductStatus } from '@prisma/client';
import { randomUUID } from 'crypto';

const prisma = new PrismaClient();

const products = [
  // FEATURED PRODUCTS
  {
    name: 'Jim Rohn Book Bundle',
    slug: 'jim-rohn-book-bundle',
    description: 'Complete collection of Jim Rohn\'s most influential books including The Five Major Pieces to the Life Puzzle, The Seasons of Life, Twelve Pillars, and more.',
    shortDesc: 'Complete Jim Rohn book collection',
    price: 181.69,
    salePrice: 97.00,
    category: ProductCategory.BUNDLES,
    imageUrl: 'https://successcom.wpenginepowered.com/wp-content/uploads/2023/jim-rohn-bundle.jpg',
    sku: 'JR-BUNDLE-001',
    stock: 100,
    featured: true,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'SUCCESS Magazine - November/December 2025 - Russell Brunson',
    slug: 'success-magazine-nov-dec-2025',
    description: 'The latest issue of SUCCESS Magazine featuring Russell Brunson',
    price: 9.99,
    category: ProductCategory.MAGAZINES,
    imageUrl: 'https://successcom.wpenginepowered.com/wp-content/uploads/2025/11/nov-dec-2025.jpg',
    sku: 'MAG-NOVDEC-2025',
    stock: 500,
    featured: true,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'The SUCCESS Starts Here Journal',
    slug: 'success-starts-here-journal',
    description: 'Your companion for tracking goals, progress, and personal development',
    price: 14.99,
    salePrice: 9.71,
    category: ProductCategory.MERCHANDISE,
    subcategory: 'Journals & Planners',
    imageUrl: 'https://successcom.wpenginepowered.com/wp-content/uploads/merch/journal.jpg',
    sku: 'MERCH-JOURNAL-001',
    stock: 250,
    featured: true,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'SUCCESS EST. 1897 Stone Cap',
    slug: 'success-stone-cap',
    description: 'Premium stone cap with SUCCESS branding',
    price: 24.99,
    category: ProductCategory.MERCHANDISE,
    subcategory: 'Apparel',
    imageUrl: 'https://successcom.wpenginepowered.com/wp-content/uploads/merch/stone-cap.jpg',
    sku: 'MERCH-CAP-001',
    stock: 150,
    featured: true,
    status: ProductStatus.ACTIVE,
  },

  // BOOKS - Jim Rohn Collection
  {
    name: 'The Jim Rohn Guides Complete Set',
    slug: 'jim-rohn-guides-complete-set',
    price: 18.71,
    category: ProductCategory.BOOKS,
    subcategory: 'Jim Rohn',
    sku: 'BOOK-JR-GUIDES',
    stock: 75,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Leading an Inspired Life by Jim Rohn',
    slug: 'leading-an-inspired-life',
    price: 34.95,
    category: ProductCategory.BOOKS,
    subcategory: 'Jim Rohn',
    sku: 'BOOK-JR-INSPIRED',
    stock: 100,
    featured: true,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'The Jim Rohn Leadership Journal',
    slug: 'jim-rohn-leadership-journal',
    price: 29.96,
    category: ProductCategory.BOOKS,
    subcategory: 'Jim Rohn',
    sku: 'BOOK-JR-JOURNAL',
    stock: 80,
    status: ProductStatus.ACTIVE,
  },
  {
    name: '7 Strategies for Wealth & Happiness by Jim Rohn',
    slug: '7-strategies-wealth-happiness',
    price: 16.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Jim Rohn',
    sku: 'BOOK-JR-7STRAT',
    stock: 120,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'The World is Yours: 26 Essays on Life and Success by Jim Rohn',
    slug: 'world-is-yours-jim-rohn',
    price: 19.95,
    category: ProductCategory.BOOKS,
    subcategory: 'Jim Rohn',
    sku: 'BOOK-JR-WORLD',
    stock: 90,
    status: ProductStatus.ACTIVE,
  },

  // BOOKS - Classics
  {
    name: 'Think and Grow Rich by Napoleon Hill',
    slug: 'think-and-grow-rich',
    description: 'The timeless classic on achieving success',
    price: 7.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Classics',
    sku: 'BOOK-TAGR',
    stock: 200,
    featured: true,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'How to Win Friends and Influence People by Dale Carnegie',
    slug: 'win-friends-influence-people',
    description: 'The essential guide to interpersonal relationships',
    price: 16.00,
    category: ProductCategory.BOOKS,
    subcategory: 'Classics',
    sku: 'BOOK-WINFRIENDS',
    stock: 150,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Tough Times Never Last, But Tough People Do! by Robert Schuller',
    slug: 'tough-times-tough-people',
    price: 8.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Personal Development',
    sku: 'BOOK-TOUGH',
    stock: 85,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'The Greatest Salesman in the World by Og Mandino',
    slug: 'greatest-salesman-world',
    price: 7.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Sales',
    sku: 'BOOK-SALESMAN',
    stock: 110,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Man\'s Search for Meaning by Viktor Frankl',
    slug: 'mans-search-meaning',
    price: 15.00,
    category: ProductCategory.BOOKS,
    subcategory: 'Philosophy',
    sku: 'BOOK-MEANING',
    stock: 95,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Maximum Achievement by Brian Tracy',
    slug: 'maximum-achievement',
    description: 'Strategies and Skills That Will Unlock Your Hidden Powers to Succeed',
    price: 18.00,
    category: ProductCategory.BOOKS,
    subcategory: 'Personal Development',
    sku: 'BOOK-MAXACH',
    stock: 75,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Awaken the Giant Within by Tony Robbins',
    slug: 'awaken-giant-within',
    description: 'How to Take Immediate Control of Your Mental, Emotional, Physical & Financial Destiny',
    price: 20.00,
    category: ProductCategory.BOOKS,
    subcategory: 'Personal Development',
    sku: 'BOOK-GIANT',
    stock: 130,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Influence: The Psychology of Persuasion by Robert Cialdini',
    slug: 'influence-psychology-persuasion',
    price: 32.50,
    category: ProductCategory.BOOKS,
    subcategory: 'Psychology',
    sku: 'BOOK-INFLUENCE',
    stock: 100,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Good to Great by Jim Collins',
    slug: 'good-to-great',
    description: 'Why Some Companies Make the Leap...and Others Don\'t',
    price: 32.50,
    category: ProductCategory.BOOKS,
    subcategory: 'Business',
    sku: 'BOOK-G2G',
    stock: 85,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Treasury of Quotes Booklet by Chris Widener',
    slug: 'treasury-quotes-widener',
    price: 4.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Reference',
    sku: 'BOOK-TREAS-CW',
    stock: 150,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Zig Ziglar\'s Little Book of Big Quotes',
    slug: 'zig-ziglar-big-quotes',
    price: 4.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Reference',
    sku: 'BOOK-ZZ-QUOTES',
    stock: 140,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Cashing Out by Julien and Kiersten Saunders',
    slug: 'cashing-out',
    description: 'Win the Wealth Game by Walking Away',
    price: 17.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Finance',
    sku: 'BOOK-CASHOUT',
    stock: 70,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Be Confident by Rocky Garza',
    slug: 'be-confident',
    description: 'A Pocket Guide to Killing Doubt and Building Conviction',
    price: 19.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Personal Development',
    sku: 'BOOK-CONFIDENT',
    stock: 80,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Convince Me by Adele Gambardella and Chip Massey',
    slug: 'convince-me',
    description: 'High-Stakes Negotiation Tactics to Get Results in Any Business Situation',
    price: 27.00,
    category: ProductCategory.BOOKS,
    subcategory: 'Business',
    sku: 'BOOK-CONVINCE',
    stock: 65,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'The Attributes by Rich Diviney',
    slug: 'the-attributes',
    description: '25 Hidden Drivers of Optimal Performance',
    price: 30.00,
    category: ProductCategory.BOOKS,
    subcategory: 'Performance',
    sku: 'BOOK-ATTR',
    stock: 75,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Think and Grow Rich: The Legacy by James Whittaker',
    slug: 'think-grow-rich-legacy',
    price: 17.99,
    category: ProductCategory.BOOKS,
    subcategory: 'Success',
    sku: 'BOOK-TAGR-LEG',
    stock: 90,
    status: ProductStatus.ACTIVE,
  },

  // COURSES
  {
    name: 'Jim Rohn\'s Foundations for Success',
    slug: 'foundations-for-success',
    description: '10-module comprehensive training program',
    price: 497.00,
    category: ProductCategory.COURSES,
    subcategory: 'Personal Development',
    sku: 'COURSE-JR-FOUND',
    stock: 999,
    featured: true,
    status: ProductStatus.ACTIVE,
  },
  {
    name: '6 Simple Steps to Creating Great Relationships',
    slug: '6-steps-great-relationships',
    price: 297.00,
    salePrice: 197.00,
    category: ProductCategory.COURSES,
    subcategory: 'Relationships',
    sku: 'COURSE-6STEPS',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Boost Your Income for Life',
    slug: 'boost-income-life',
    price: 297.00,
    salePrice: 197.00,
    category: ProductCategory.COURSES,
    subcategory: 'Finance',
    sku: 'COURSE-BOOST',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Building a Brand Identity that Breaks Through the Noise',
    slug: 'brand-identity-course',
    price: 297.00,
    salePrice: 197.00,
    category: ProductCategory.COURSES,
    subcategory: 'Marketing',
    sku: 'COURSE-BRAND',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Brian Tracy\'s Success Mastery Academy',
    slug: 'success-mastery-academy',
    price: 199.00,
    category: ProductCategory.COURSES,
    subcategory: 'Success',
    sku: 'COURSE-BT-MASTER',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Coach Wooden\'s Competitive Greatness',
    slug: 'coach-wooden-competitive-greatness',
    price: 97.00,
    category: ProductCategory.COURSES,
    subcategory: 'Leadership',
    sku: 'COURSE-CW-COMP',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Jim Rohn Weekend Leadership Event',
    slug: 'weekend-leadership-event',
    price: 297.00,
    salePrice: 177.00,
    category: ProductCategory.COURSES,
    subcategory: 'Leadership',
    sku: 'COURSE-JR-WEEKEND',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Big Picture Thinking',
    slug: 'big-picture-thinking',
    price: 79.00,
    category: ProductCategory.COURSES,
    subcategory: 'Thinking',
    sku: 'COURSE-BIGPIC',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'How Successful People Think',
    slug: 'successful-people-think',
    price: 199.00,
    category: ProductCategory.COURSES,
    subcategory: 'Success',
    sku: 'COURSE-THINK',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Twelve Pillars: The Skills You Need to Succeed',
    slug: 'twelve-pillars-course',
    price: 199.00,
    category: ProductCategory.COURSES,
    subcategory: 'Success',
    sku: 'COURSE-12PIL',
    stock: 999,
    status: ProductStatus.ACTIVE,
  },

  // MERCHANDISE
  {
    name: 'SUCCESS Classic Covers 15-oz. Ceramic Mug',
    slug: 'classic-covers-mug',
    price: 14.99,
    category: ProductCategory.MERCHANDISE,
    subcategory: 'Drinkware',
    sku: 'MERCH-MUG-001',
    stock: 200,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Tote Bag',
    slug: 'success-tote-bag',
    price: 26.95,
    category: ProductCategory.MERCHANDISE,
    subcategory: 'Bags',
    sku: 'MERCH-TOTE-001',
    stock: 150,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Laptop Sleeve',
    slug: 'laptop-sleeve',
    price: 24.95,
    category: ProductCategory.MERCHANDISE,
    subcategory: 'Tech Accessories',
    sku: 'MERCH-LAPTOP-001',
    stock: 100,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Jim Rohn One-Year Success Planner',
    slug: 'jim-rohn-success-planner',
    price: 49.95,
    category: ProductCategory.MERCHANDISE,
    subcategory: 'Planners',
    sku: 'MERCH-PLANNER-JR',
    stock: 120,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'Lessons on Life Gift Book by Jim Rohn',
    slug: 'lessons-life-gift-book',
    price: 19.95,
    salePrice: 9.97,
    category: ProductCategory.MERCHANDISE,
    subcategory: 'Gift Books',
    sku: 'MERCH-LESSONS',
    stock: 80,
    status: ProductStatus.ACTIVE,
  },

  // MAGAZINES
  {
    name: 'SUCCESS Magazine September/October 2025 - Maria Menounos',
    slug: 'success-mag-sep-oct-2025',
    price: 9.99,
    category: ProductCategory.MAGAZINES,
    sku: 'MAG-SEPOCT-2025',
    stock: 400,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'SUCCESS Magazine July/August 2025 - Tim and Demi-Leigh Tebow',
    slug: 'success-mag-jul-aug-2025',
    price: 9.99,
    category: ProductCategory.MAGAZINES,
    sku: 'MAG-JULAUG-2025',
    stock: 350,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'SUCCESS Magazine May/June 2025 - Nick Cannon',
    slug: 'success-mag-may-jun-2025',
    price: 9.99,
    category: ProductCategory.MAGAZINES,
    sku: 'MAG-MAYJUN-2025',
    stock: 300,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'SUCCESS Magazine March/April 2025 - Mel Robbins',
    slug: 'success-mag-mar-apr-2025',
    price: 9.99,
    category: ProductCategory.MAGAZINES,
    sku: 'MAG-MARAPR-2025',
    stock: 280,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'SUCCESS Magazine January/February 2025 - Wilmer Valderrama',
    slug: 'success-mag-jan-feb-2025',
    price: 9.99,
    category: ProductCategory.MAGAZINES,
    sku: 'MAG-JANFEB-2025',
    stock: 250,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'SUCCESS Magazine November/December 2024 - Eva Longoria',
    slug: 'success-mag-nov-dec-2024',
    price: 9.99,
    salePrice: 3.97,
    category: ProductCategory.MAGAZINES,
    sku: 'MAG-NOVDEC-2024',
    stock: 150,
    status: ProductStatus.ACTIVE,
  },
  {
    name: 'SUCCESS Magazine September/October 2024 - Daymond John',
    slug: 'success-mag-sep-oct-2024',
    price: 9.99,
    salePrice: 3.97,
    category: ProductCategory.MAGAZINES,
    sku: 'MAG-SEPOCT-2024',
    stock: 120,
    status: ProductStatus.ACTIVE,
  },
];

async function main() {
  console.log('Seeding products...');

  for (const product of products) {
    await prisma.products.upsert({
      where: { slug: product.slug },
      update: product,
      create: {
        ...product,
        id: randomUUID(),
        updatedAt: new Date(),
      },
    });
  }

  console.log(`Seeded ${products.length} products successfully!`);
}

main()
  .catch((e) => {
    console.error('Error seeding products:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
